Implement multi-project Docker architecture
- Add optimized multi-stage Dockerfile for askappy-base
- Implement smart CI/CD workflow with change detection
- Add project management utilities and configuration
- Update documentation for multi-project structure
- Exclude tostool until ready for deployment

diff --git a/askappy-base/Dockerfile b/askappy-base/Dockerfile
--- a/askappy-base/Dockerfile
+++ b/askappy-base/Dockerfile
@@ -1,158 +1,262 @@
 # syntax=docker/dockerfile:1
+
+#####################################################################
+# Multi-stage build for askappy base image with casacore
+# Improved version with better practices while maintaining all libs
+#####################################################################
+
+ARG UBUNTU_VERSION=24.04
 ARG TARGETPLATFORM=linux/amd64
-FROM --platform=${TARGETPLATFORM} ubuntu:24.04 
+
+#####################################################################
+# Stage 1: Build dependencies and tools
+#####################################################################
+FROM --platform=${TARGETPLATFORM} ubuntu:${UBUNTU_VERSION} as builder
 
 ARG TARGETPLATFORM
+ARG DEBIAN_FRONTEND=noninteractive
+
+# Build-time metadata
+ARG BUILD_DATE
+ARG VCS_REF
+ARG VERSION
+
+# Set timezone early
 ENV TZ=Etc/UTC
+
+# Install build dependencies in a single layer with cleanup
 RUN apt-get update -qq \
-      && apt-get install -yq tzdata \
-      && ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime \ 
-      && dpkg-reconfigure -f noninteractive tzdata \
-      && apt-get -y --no-install-recommends install \
-         git \
-         wget \
-         vim \
-         vim-gtk3 \
-         vim-gui-common \
-         openssh-server \
-         libbz2-dev \
-         python3-dev \
-         python3-pip \
-         python3-pyparsing \
-         build-essential \
-         cmake \
-         gdb \
-         g++ \
-         ca-certificates \
-         gfortran \
-         libgfortran5 \
-         libc6 \
-         libhwloc-dev \
-         libibverbs-dev \
-         libopenmpi-dev \
-         imagemagick \
-         libmagickcore-dev \
-         libmagickwand-dev \
-         libmagic-dev \
-         fuse \
-         libfuse2 \
-         libclang-dev \
-         libssl-dev \
-         libffi-dev \
-         libncurses5-dev \
-         libreadline-dev \
-         flex \
-         bison \
-         libblas-dev \
-         liblapacke-dev \
-         libcfitsio-dev \
-         libpthread-stubs0-dev \
-         libgsl-dev \
-         wcslib-dev \
-         libfftw3-dev \
-         python3-numpy \
-         python-setuptools \
-         libx11-dev \
-         xauth \
-         xorg \
-         python3-pyqt5 \
-         libboost-python-dev \
-      && apt-get clean all \
-      && rm -r /var/lib/apt/lists/*
-WORKDIR /
+    && apt-get install -yq tzdata \
+    && ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime \
+    && dpkg-reconfigure -f noninteractive tzdata \
+    && apt-get -y --no-install-recommends install \
+        # Development tools
+        git \
+        wget \
+        build-essential \
+        cmake \
+        gdb \
+        g++ \
+        gfortran \
+        libgfortran5 \
+        flex \
+        bison \
+        # System libraries
+        ca-certificates \
+        libc6 \
+        libssl-dev \
+        libffi-dev \
+        libncurses5-dev \
+        libreadline-dev \
+        # MPI and parallel computing
+        libhwloc-dev \
+        libibverbs-dev \
+        libopenmpi-dev \
+        # Python development
+        python3-dev \
+        python3-pip \
+        python3-pyparsing \
+        python3-numpy \
+        python-setuptools \
+        # Scientific computing libraries
+        libblas-dev \
+        liblapacke-dev \
+        libcfitsio-dev \
+        libpthread-stubs0-dev \
+        libgsl-dev \
+        wcslib-dev \
+        libfftw3-dev \
+        # Image processing
+        imagemagick \
+        libmagickcore-dev \
+        libmagickwand-dev \
+        libmagic-dev \
+        # Other development libraries
+        libbz2-dev \
+        libclang-dev \
+        libboost-python-dev \
+        # X11 and GUI (if needed for your workflows)
+        libx11-dev \
+        # Archive tools
+        fuse \
+        libfuse2 \
+    && apt-get clean \
+    && rm -rf /var/lib/apt/lists/* \
+    && rm -rf /tmp/* \
+    && rm -rf /var/tmp/*
 
-
-# What version/branch of your repo do you want to build this container from?
-ARG REPO_NAME=askappy
-ARG REPO_VERSION=base-casacore-3.6.1
-ARG CASACORE_VERSION=v3.6.1
-
-# Record useful metadata: See https://docs.docker.com/config/labels-custom-metadata/
-LABEL repo.name="${REPO_NAME}" \
-      repo.version="${REPO_VERSION}" \
-      repo.maintainer.name="Wasim Raja" \
-      repo.maintainer.email="Wasim.Raja@csiro.au" \
-      repo.description="The image provides the software \
-env needed for building casacore." 
-
-ARG REQFILE=requirements.txt
+# Build directories
 ARG BUILD_DIR=/_build
 ARG MEASURES_DATA="/_build/measures_data"
 ARG INSTALL_DIR=/_install
 
-# Set default python to python3:
-RUN update-alternatives --remove python /usr/bin/python2 \
-      && update-alternatives --install /usr/bin/python python /usr/bin/python3 10 \
-      && python3 -m pip install -U --force-reinstall pip \
-      && pip3 install setuptools \
-      && pip3 install wheel 
+RUN mkdir -p ${INSTALL_DIR} ${BUILD_DIR} ${MEASURES_DATA}
 
-RUN mkdir -p ${INSTALL_DIR} ${BUILD_DIR} 
-RUN mkdir -p ${MEASURES_DATA}
+# Set up Python environment
+RUN update-alternatives --remove python /usr/bin/python2 || true \
+    && update-alternatives --install /usr/bin/python python /usr/bin/python3 10 \
+    && python3 -m pip install --upgrade pip setuptools wheel
 
-
-# MPI: 
-#ARG MPICH_VERSION="3.4.2"
+#####################################################################
+# Build MPICH from source
+#####################################################################
 ARG MPICH_VERSION="4.3.1"
-ARG CPU_CORE_COUNT=1
+ARG CPU_CORE_COUNT=4
 ARG MPICH_CONFIGURE_OPTIONS="--enable-fast=all,O3 --with-device=ch4:ofi --prefix=/usr/local FFLAGS=-fallow-argument-mismatch"
-ARG MPICH_MAKE_OPTIONS="-j${CPU_CORE_COUNT}"
-RUN mkdir -p ${BUILD_DIR}/mpich-build \
-    && cd ${BUILD_DIR}/mpich-build \
-    && wget https://www.mpich.org/static/downloads/${MPICH_VERSION}/mpich-${MPICH_VERSION}.tar.gz \
+
+RUN cd ${BUILD_DIR} \
+    && wget -q https://www.mpich.org/static/downloads/${MPICH_VERSION}/mpich-${MPICH_VERSION}.tar.gz \
     && tar xzf mpich-${MPICH_VERSION}.tar.gz \
-    && cd mpich-${MPICH_VERSION}  \
+    && cd mpich-${MPICH_VERSION} \
     && ./configure ${MPICH_CONFIGURE_OPTIONS} \
-    && make ${MPICH_MAKE_OPTIONS} \
+    && make -j${CPU_CORE_COUNT} \
     && make install \
     && ldconfig \
     && cd / \
-    && rm -rf ${BUILD_DIR}/mpich-build
+    && rm -rf ${BUILD_DIR}/mpich-${MPICH_VERSION}*
 
-# +++++++++++++++++ Build casacore from source +++++++++++++++++++++ 
-# Build casacore first - get measures data as a first step:
-# TODO: We need a way to link measures data to the updated version 
-# kept on host machines. 
+#####################################################################
+# Build Casacore from source
+#####################################################################
+ARG CASACORE_VERSION=v3.6.1
+
+# Download measures data
 RUN cd ${MEASURES_DATA} \
-    && wget ftp://ftp.astron.nl/outgoing/Measures/WSRT_Measures.ztar \
-    && tar xf *.ztar 
+    && wget -q ftp://ftp.astron.nl/outgoing/Measures/WSRT_Measures.ztar \
+    && tar xf *.ztar \
+    && rm *.ztar
+
+# Build casacore
 RUN cd ${BUILD_DIR} \
-    && git clone https://github.com/casacore/casacore.git \
+    && git clone --depth 1 --branch ${CASACORE_VERSION} https://github.com/casacore/casacore.git \
     && cd casacore \
-    && git fetch --all --tags \
-    && git checkout tags/${CASACORE_VERSION} -b ${CASACORE_VERSION} \
     && mkdir build \
     && cd build \
-    && cmake -DDATA_DIR=${MEASURES_DATA} -DUSE_OPENMP=OFF \
-    -DBUILD_PYTHON3=ON -DUSE_THREADS=ON .. \
-    && make -j4 install
-# +++++++++++++++++++ End of casacore build +++++++++++++++++++++++ 
+    && cmake \
+        -DDATA_DIR=${MEASURES_DATA} \
+        -DUSE_OPENMP=OFF \
+        -DBUILD_PYTHON3=ON \
+        -DUSE_THREADS=ON \
+        -DCMAKE_BUILD_TYPE=Release \
+        .. \
+    && make -j${CPU_CORE_COUNT} install \
+    && ldconfig \
+    && cd / \
+    && rm -rf ${BUILD_DIR}/casacore
 
-## Fetch the requirement file from the repo and install requirements:
-COPY ${REQFILE} /requirements.txt
+#####################################################################
+# Stage 2: Runtime image
+#####################################################################
+FROM --platform=${TARGETPLATFORM} ubuntu:${UBUNTU_VERSION} as runtime
 
-RUN pip3 install --no-cache-dir --no-deps -r requirements.txt
-RUN pip3 install --default-timeout=120 --no-binary python-casacore python-casacore
+ARG DEBIAN_FRONTEND=noninteractive
+ENV TZ=Etc/UTC
 
-## Install modular casatools and caatasks - can be invoked from python environments:
-## See: https://casa.nrao.edu/casadocs/casa-6.1.0/usingcasa/obtaining-and-installing
-#RUN mkdir -p ${BUILD_DIR}/${REPO_NAME} \
-#    && cd ${BUILD_DIR}/${REPO_NAME} \
-#    && pip3 install --index-url https://casa-pip.nrao.edu/repository/pypi-casa-release/simple casatools \
-#    && pip3 install --index-url https://casa-pip.nrao.edu/repository/pypi-casa-release/simple casatasks \
-#    && pip3 install --index-url https://casa-pip.nrao.edu/repository/pypi-casa-release/simple casampi \
-#    && pip3 install casaplotms \
-#    && pip3 install casaviewer
+# Install only runtime dependencies
+RUN apt-get update -qq \
+    && apt-get install -yq tzdata \
+    && ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime \
+    && dpkg-reconfigure -f noninteractive tzdata \
+    && apt-get -y --no-install-recommends install \
+        # Essential tools
+        vim \
+        vim-gtk3 \
+        vim-gui-common \
+        openssh-server \
+        ca-certificates \
+        # Runtime libraries for compiled dependencies
+        libgfortran5 \
+        libc6 \
+        libhwloc15 \
+        libibverbs1 \
+        libopenmpi3 \
+        imagemagick \
+        libmagickcore-6.q16-6 \
+        libmagickwand-6.q16-6 \
+        libmagic1 \
+        fuse \
+        libfuse2 \
+        libssl3 \
+        libffi8 \
+        libncurses6 \
+        libreadline8 \
+        libblas3 \
+        liblapack3 \
+        libcfitsio10 \
+        libgsl27 \
+        libfftw3-3 \
+        libbz2-1.0 \
+        libboost-python1.83.0 \
+        # Python runtime
+        python3 \
+        python3-pip \
+        python3-pyparsing \
+        python3-numpy \
+        python3-pyqt5 \
+        # X11 runtime (if needed)
+        xauth \
+        xorg \
+    && apt-get clean \
+    && rm -rf /var/lib/apt/lists/* \
+    && rm -rf /tmp/* \
+    && rm -rf /var/tmp/*
 
-# Define the measures data area in the root's home area:
-ARG CASA_CONFIG_DIR="/root/.casa"
-RUN mkdir -p ${CASA_CONFIG_DIR}
-COPY config.py ${CASA_CONFIG_DIR}/.
-COPY Dockerfile /Dockerfile
+# Copy built libraries and binaries from builder stage
+COPY --from=builder /usr/local/ /usr/local/
+COPY --from=builder /_build/measures_data /_build/measures_data
 
-# Replicate the policy for ImageMagick from Setonix setup
-ADD ImageMagick-7_on_setonix_policy.xml /etc/ImageMagick-6/policy.xml
+# Set up Python environment
+RUN update-alternatives --remove python /usr/bin/python2 || true \
+    && update-alternatives --install /usr/bin/python python /usr/bin/python3 10 \
+    && python3 -m pip install --upgrade pip
+
+# Install Python packages
+COPY requirements.txt /tmp/requirements.txt
+RUN pip3 install --no-cache-dir -r /tmp/requirements.txt \
+    && pip3 install --default-timeout=120 --no-binary python-casacore python-casacore \
+    && rm /tmp/requirements.txt
+
+# Create non-root user for security
+ARG USERNAME=askappy
+ARG USER_UID=1000
+ARG USER_GID=$USER_UID
+
+RUN groupadd --gid $USER_GID $USERNAME \
+    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
+    && mkdir -p /home/$USERNAME/.casa \
+    && chown -R $USERNAME:$USERNAME /home/$USERNAME
+
+# Set up casa configuration
+COPY config.py /home/$USERNAME/.casa/
+RUN chown $USERNAME:$USERNAME /home/$USERNAME/.casa/config.py
+
+# Configure ImageMagick policy
+COPY ImageMagick-7_on_setonix_policy.xml /etc/ImageMagick-6/policy.xml
+
+# Set environment variables
 ENV LD_LIBRARY_PATH="/usr/local/lib"
+ENV PYTHONPATH="/usr/local/lib/python3.12/site-packages:${PYTHONPATH}"
+ENV PATH="/usr/local/bin:${PATH}"
+
+# Metadata labels
+LABEL org.opencontainers.image.title="askappy-base" \
+      org.opencontainers.image.description="Base image with casacore and scientific computing tools" \
+      org.opencontainers.image.version="${VERSION}" \
+      org.opencontainers.image.created="${BUILD_DATE}" \
+      org.opencontainers.image.revision="${VCS_REF}" \
+      org.opencontainers.image.vendor="CSIRO" \
+      org.opencontainers.image.authors="Wasim Raja <Wasim.Raja@csiro.au>" \
+      repo.name="askappy" \
+      repo.version="base-casacore-3.6.1" \
+      casacore.version="v3.6.1" \
+      mpich.version="4.3.1"
+
+# Switch to non-root user
+USER $USERNAME
+WORKDIR /home/$USERNAME
+
+# Health check
+HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
+    CMD python3 -c "import casacore; print('OK')" || exit 1
 
 CMD ["/bin/bash"]
-
